### ISSUE TITLE
pyarrow 0.13 not compatible with write_gcr_to_parquet

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/DC2-production#381]
https://github.com/LSSTDESC/DC2-production/blob/d9380973d08152ba8e7948eda3d3afe0f36b4caf/scripts/write_gcr_to_parquet.py#L99-L100

These two lines cause a crash at execution : `TypeError: __cinit__() got an unexpected keyword argument 'append'` and `TypeError: __cinit__() got an unexpected keyword argument 'file_scheme'`

**Comment by heather999** [comment]
And that's a problem if we need to move to some later version of pyarrow - DM is currently "stuck" at 0.13.0 so we cannot just upgrade within the stack conda env.  Either the script has to be modified to work with pyarrow 0.13.0, or we set up another conda env specifically to run `write_gcr_to_parquet.py` using whatever version of pyarrow is needed.

**Comment by johannct** [comment]
I think that our scripts are too old for 0.13, not the contrary.

**Comment by yymao** [comment]
`write_gcr_to_parquet.py` has been updated and this issue should be sovled.
